### ISSUE TITLE
Would it make sense to have assert_err_eq?

### ISSUE THREAD

**Issue by gyzerok** [svartalf/rust-claim#7]
Hello and thanks for a awesome crate! 🎉 

While writing my tests and using `claim` I've started wondering whether there should be an `assert_err_eq` function. It feels like I don't only want to check if my result is an error, but that it is a specific error.

Any specific reason why such macro is missing?

**Comment by Anders429** [comment]
I've also wondered about this. Several times I've wanted to use something similar to `assert_ok_eq` to check that an `Err` contains an expected value.

**Comment by Anders429** [comment]
FYI, this macro is now published in the [fork](https://github.com/mattwilkinsonn/rust-claims) @mattwilkinsonn put together: https://crates.io/crates/claims
